### ISSUE TITLE
Downloading GPG keys locally fails due to permissions issue

### ISSUE THREAD

**Issue by KB1RD** [Turgon37/ansible-mariadb-server#8]
Hi, I encountered a small issue installing on Debian. Ansible will fail and print the following text when trying to add the MariaDB GPG keys:
```
FAILED - RETRYING: Download MariaDB repository GPG key into local folder (5 retries left).
FAILED - RETRYING: Download MariaDB repository GPG key into local folder (4 retries left).
FAILED - RETRYING: Download MariaDB repository GPG key into local folder (3 retries left).
FAILED - RETRYING: Download MariaDB repository GPG key into local folder (2 retries left).
FAILED - RETRYING: Download MariaDB repository GPG key into local folder (1 retries left).
failed: [67.205.171.132 -> localhost] (item={u'url': u'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x177F4010FE56CA3336300305F1656F24C74CD1D8', u'id': u'177F4010FE56CA3336300305F1656F24C74CD1D8'}) => {"ansible_loop_var": "item", "attempts": 5, "changed": false, "item": {"id": "177F4010FE56CA3336300305F1656F24C74CD1D8", "url": "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x177F4010FE56CA3336300305F1656F24C74CD1D8"}, "module_stderr": "Sorry, try again.\n[sudo via ansible, key=whvpesmnvoxkyhzuvchyhxbyajuvmcvo] password:\nsudo: 1 incorrect password attempt\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```
I ran this rule in isolation and I have traced the error. The key is that it says "sudo: 1 incorrect password." As seen here, the first task in install-Debian-x86_64.yml runs locally:
https://github.com/Turgon37/ansible-mariadb-server/blob/15cc6b83e0f6ed092ca62557c1efad27b5d5cc86/tasks/install-Debian-x86_64.yml#L26
However, in playbooks where `become: true` is set, this will attempt to sudo with an invalid password on the user's machine. To fix this problem, `become: false` should be added to this task and any others running on the local machine or that should not need sudo privileges. If I add this just after line 26 (shown above), this fixes the problem. I'm not sure yet if this impacts other distros. I'll look into creating a pull request in a few days.

**Comment by Turgon37** [comment]
I've pushed a version 1.0.1 of this role, can you tell me if it solve your issue ?

**Comment by KB1RD** [comment]
Thank you! That works perfectly!
